models/Eatery.py
from config import db, ma

class Eatery(db.Model):
    __tablename__ = "eatery"
    id_eatery = db.Column(db.Integer, primary_key=True, autoincrement=True)
    eatery_name = db.Column(db.String(20), nullable=False)
    cuisine = db.Column(db.String(20), nullable=False)
    url_image = db.Column(db.String(300), nullable=False)
    url_maps = db.Column(db.String(300), nullable=False)
    address = db.Column(db.String)
    phone = db.Column(db.String(20))
    description = db.Column(db.String)

    __table_args__ = (
        db.Index('idx_eatery_name', "eatery_name"),
    )

class EaterySchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Eatery
        load_instance = True
        sql_session = db.session

eatery_schema = EaterySchema()
eateries_schema = EaterySchema(many=True)

models/Saucers.py
from config import db, ma
from marshmallow_sqlalchemy import fields
from .Eatery import Eatery, EaterySchema

class Saucer(db.Model):
    __tablename__ = 'saucers'
    id_saucer = db.Column(db.Integer, primary_key=True, autoincrement=True)
    id_eatery = db.Column(db.Integer, db.ForeignKey('eatery.id_eatery'), nullable=False)
    saucer_name = db.Column(db.String(30), nullable=False, index=True)
    price = db.Column(db.Float, nullable=False)
    description = db.Column(db.Text)
    url_image = db.Column(db.String(255))
    eatery = db.relationship('Eatery', foreign_keys=[id_eatery])
    __table_args__ = (
        db.UniqueConstraint('id_eatery', 'saucer_name', name='uq_saucer_name_per_eatery'),
        db.Index('idx_saucer_name', "saucer_name"),
        )

    
class SaucerSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Saucer
        load_instance = True
        sql_session = db.session
    
    # eatery = fields.Nested(EaterySchema, only=('id_eatery', 'eatery', 'cuisine', 'url_image', 'url_maps'))
    eatery = fields.Nested(EaterySchema)

saucer_schema = SaucerSchema()
saucers_schema = SaucerSchema(many=True)

models/User.py
from marshmallow_sqlalchemy import fields
from config import db, ma

class User(db.Model):
    __tablename__ = "users"
    id_user = db.Column(db.Integer, primary_key=True, autoincrement=True)
    names = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(32), unique=True)
    password = db.Column(db.String(162), nullable=False)
    datebirth = db.Column(db.String(32))


class UserSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = User
        load_instance = True
        sql_session = db.session

user_schema = UserSchema()
# parameter many=True tells to UserSchema
# to expect an iterable to serialize
users_schema = UserSchema(many=True)

models/__init__.py
from .User import User, user_schema, users_schema
from .Eatery import Eatery, eatery_schema, eateries_schema
from .Saucers import Saucer, saucer_schema, saucers_schema

__all__ = [
    User, user_schema, users_schema,
    Eatery, eatery_schema, eateries_schema,
    Saucer, saucer_schema, saucers_schema
]

app.py
from flask_wtf.csrf import CSRFProtect
from pages import pages_bp
from searchs import search_bp
from errors import errors_bp
from config import connex_app

app = connex_app.app
csrf = CSRFProtect(app)

app.register_blueprint(pages_bp,  url_prefix='/')
app.register_blueprint(errors_bp, url_prefix='/')
app.register_blueprint(search_bp, url_prefix='/')


if __name__ == '__main__':
    csrf.init_app(app)
    app.run(debug=True)

routes/pages.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import LoginManager, login_user, logout_user, login_required
from models import User
from config import connex_app
from services import CheckLogin, UserLogin
import logging

pages_bp = Blueprint('pages', __name__, template_folder='templates', static_folder='static')


login_manager = LoginManager(connex_app.app)

@login_manager.user_loader
def load_user(email):
    return UserLogin.get_user_by_email(email)

@pages_bp.route('/')
def index():
    return render_template('index.html')

@pages_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user = CheckLogin(request.form['email'], request.form['password'])
        logged_user = UserLogin.login(user)

        if logged_user:
            login_user(logged_user)
            return redirect(url_for('pages.index'))
        else:
            flash('Usuario o contraseña incorrectos')
            return redirect(url_for('pages.login'))
    else:
        return render_template('login.html')

@pages_bp.route('/register')
def register():
    return render_template('register.html')

@pages_bp.route('/menus')
def menus():
    return render_template('menus.html')

@pages_bp.route('/resturant')
def restaurant():
    return render_template('restaurant.html')

@pages_bp.route('/faq')
def faq():
    return render_template('faq.html')

@pages_bp.route('/blog')
def blog():
    return render_template('blog.html')

@pages_bp.route('/contac')
def contac():
    return render_template('contac.html')

@pages_bp.route('/about')
def about():
    return render_template('about.html')

@pages_bp.route('/filos')
def filos():
    return render_template('filos.html')

@pages_bp.route('/registro')
def registro():
    return render_template('registro.html')

@pages_bp.route('/40x')
def err_404(error):
    return render_template('40x.html')

services/__init__.py
from .users import UserLogin, CheckLogin, UserRegister, create, update, delete, read_all, read_one
from .saucers import SearchSaucer
from .eateries import SearchEatery

__all__ = [
    UserLogin, CheckLogin, UserRegister, create, update, delete, read_all, read_one,
    SearchSaucer,
    SearchEatery
]

templates/Registro.html
{% extends './base.html' %}

{% block title %}TuComida - {{ super() }}{% endblock %}

{% block customCSS %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/registro.css')}}" />
  <link rel="stylesheet" href="{{url_for('static', filename='css/cards.css')}}" />

{% endblock %}
{% block content %}
  <body>

    <section class="banner">
      <div class="banner-container">
        <h2>Registra tu Restaurante</h2>
        <form enctype="multipart/form-data">
            <div class="form-group">
                <label for="nombre">Nombre de Restaurante</label><br>
                <input type="text" id="nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="categoria">Categoría o Tipo de Cocina</label><br>
                <input type="text" id="categoria" name="categoria" required>
            </div>
            <div class="form-group">
                <label for="direccion">Dirección</label><br>
                <input type="text" id="direccion" name="direccion" required>
                <a href="https://www.google.com/maps" target="_blank">Agregar Ubicación en Google Maps</a>
            </div>
            <div class="form-group">
                <label for="telefono">Número de Teléfono</label><br>
                <input type="tel" id="telefono" name="telefono" required>
            </div>
            <div class="form-group">
                <label for="correo">Correo Electrónico</label><br>
                <input type="email" id="correo" name="correo" required>
            </div>
            <div class="form-group">
                <label for="horario">Horario</label><br>
                <input type="text" id="horario" name="horario" required>
            </div>
            <div class="form-group">
                <label for="precio">Rango de Precios</label>
                <select id="precio" name="precio" required>
                    <option value="economico">Económico</option>
                    <option value="moderado">Moderado</option>
                    <option value="caro">Caro</option>
                </select>
            </div>
            <div class="form-group">
                <label for="fotos-interior">Fotos del Restaurante (Interior)</label>
                <input type="file" id="fotos-interior" name="fotos-interior" accept="image/*" required>
            </div>
            <div class="form-group">
                <label for="fotos-exterior">Fotos del Restaurante (Exterior)</label>
                <input type="file" id="fotos-exterior" name="fotos-exterior" accept="image/*" required>
            </div>
            <div class="form-group">
                <label for="fotos-decoracion">Fotos del Restaurante (Decoración)</label>
                <input type="file" id="fotos-decoracion" name="fotos-decoracion" accept="image/*" required>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripción del Restaurante</label><br>
                <textarea id="descripcion" name="descripcion" rows="4" required></textarea>
            </div>
            <div class="form-group">
                <label for="redes-sociales">Redes Sociales</label><br>
                <input type="text" id="redes-sociales" name="redes-sociales">
            </div>
            <div class="form-group">
                <label for="contacto-adicional">Información de Contacto Adicional (Otras Sucursales, etc.)</label><br>
                <textarea id="contacto-adicional" name="contacto-adicional" rows="4"></textarea>
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="confirm-password">Confirmar Contraseña</label>
                <input type="password" id="confirm-password" name="confirm-password" required>
            </div>
            <div class="form-group">
        <label for="terminos-condiciones">
            <input type="checkbox" id="terminos-condiciones" name="terminos-condiciones" required>Acepto los términos y condiciones</label>
    </div>
            <div class="form-group">
                <button type="submit">Registrar Restaurante</button>
            </div>
        </form>
    </section>
    </body>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0,user-scalable=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/967737f4f0.js"
      crossorigin="anonymous"
    ></script>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="icon" href="https://cdn.glitch.global/d2f60e58-9efe-4a05-bb88-fd4999848107/logo.png?v=1702022066496" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}" />
    {% block customCSS %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class=flashes>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        {% endif %}
    {% endwith %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand logo" href="{{url_for('pages.index')}}">
          <img src="https://cdn.glitch.global/d2f60e58-9efe-4a05-bb88-fd4999848107/logo.png?v=1702022066496" alt="TuComida" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('pages.index')}}"
                >Inicio</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('pages.menus')}}">Restaurantes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('pages.ofertas')}}">Ofertas</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Conocenos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{url_for('pages.blog')}}">Opiniones</a></li>
                <li>
                  <a class="dropdown-item" href="{{url_for('pages.faq')}}"
                    >Preguntas frecuentes</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{{url_for('pages.contac')}}"
                    >Contáctanos</a
                  >
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="{{url_for('pages.about')}}"
                    >Acerca de nosotros</a
                  >
                </li>
              </ul>
            </li>
            <!-- <li class="nav-item">
                  <a class="nav-link disabled">Disabled</a>
                </li> -->
          </ul>
          <form method="POST" action="{{url_for('searchs.searchsaucer')}}" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="search" id="search" name="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
          </form>
          <div class="actions">
            <a href="{{url_for('pages.login')}}" class="actions-btn">Iniciar sesión</a>
            <a href="{{url_for('pages.register')}}" class="actions-btn2">Registrarse</a>
          </div>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
    
    <footer class="footer">
      <div class="group-1">
        <div class="box">
          <figure>
            <a
              href="https://www.instagram.com/lasalsona/"
              target="_blank"
              rel="noreferrer noopener"
            >
              <img src="https://cdn.glitch.global/d2f60e58-9efe-4a05-bb88-fd4999848107/logo.png?v=1702022066496" alt="TuComida" />
            </a>
          </figure>
        </div>
        <div class="box">
          <h2>SOBRE NOSOTROS</h2>
          <a href="{{url_for('pages.about')}}" class="textlink">
            <p>¿Quiénes somos?</p>
          </a>
          <a href="{{url_for('pages.filos')}}" class="textlink">
            <p>Nuestra misión</p>
          </a>
          <a href="{{url_for('pages.faq')}}" class="textlink">
            <p>Preguntas frecuentes</p>
          </a>
          <a href="{{url_for('pages.contac')}}" class="textlink">
            <p>Contáctanos</p>
          </a>
        </div>
        <div class="box">
          <h2>SÍGUENOS</h2>
          <div class="red-social">
            <div class="icons">
              <a
                href="https://www.instagram.com/lasalsona/"
                target="_blank"
                rel="noreferrer noopener"
                class="icon icon--instagram"
              >
                <i class="fa fa-instagram"></i>
              </a>
              <a
                href="#"
                target="_blank"
                rel="noreferrer noopener"
                class="icon icon--twitter"
              >
                <i class="fa fa-twitter"></i>
              </a>
              <a
                href="https://www.facebook.com/profile.php?id=100095026651686"
                target="_blank"
                rel="noreferrer noopener"
                class="icon icon--facebook"
              >
                <i class="fa fa-facebook"></i>
              </a>
              <a
                href="#"
                target="_blank"
                rel="noreferrer noopener"
                class="icon icon--youtube"
              >
                <i class="fa fa-youtube"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="group-2">
        <small> &copy; 2023 <b>TuComida: Tú Come </b> </small>
      </div>
      <div class="group-3">
        <small> Made with 😻 by Gatovsky </small>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

templates/eatery.html
{% extends './base.html' %}

{% block title %}
  TuComida - {{ super() }}
{% endblock %}

{% block customCSS %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/restaurant.css')}}">
{% endblock %}

{% block content %}
  <body>
    <div class="restaurant-profile">
      <div class="cover-photo">
        <img src="{{eatery['url_image']}}" alt="Portada del restaurante" />
        <div class="profile-photo">
          <img src="{{eatery['url_image']}}" alt="Foto de perfil del restaurante" />
        </div>
      </div>
      <h3>{{eatery['eatery']}}</h3>
      <div class="restaurant-hours">
        <h4>Horario del Restaurante</h4>
        <p>Lunes a Viernes: 10:00 AM - 10:00 PM</p>
        <p>Sábado y Domingo: 11:00 AM - 9:00 PM</p>
      </div>

    <!-- <div class="menu-options">
      <div class="category-content" id="all-content"></div>
    </div>
    <div class="category-content" id="adults-content">
      <h5>{{eatery['cuisine']}}</h5>
      <div class="menu-items">
        <div class="menu-item">
          <a href="{{url_for('pages.plato')}}">
            <div class="item-details">
              <img src="https://s7d1.scene7.com/is/image/mcdonalds/202201_3426-005_DoubleQuarterPounderwithCheese_832x472:1-4-product-tile-desktop" alt="Hamburguesa 1" />
              <div class="item-details-text">
                <h4>Hamburguesa Clásica</h4>
                <p>Una hamburguesa deliciosa con todos los ingredientes clásicos.</p>
              </div>
            </div>
          </a>
        </div> -->

    <!-- Nuevo div con ubicación geográfica y detalles -->
    <div class="location-details">
      <iframe
        class="map"
        src="{{eatery['url_maps']}}"
        width="auto"
        height="auto"
        style="border: 0"
        allowfullscreen=""
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
      ></iframe>
      <div style="padding-left: 1rem; padding-top: 2rem">
        <h3>Ubicación</h3>
        <p>Dirección: {{eatery['address']}}</p>
        <p>Teléfono: {{eatery['phone']}}</p>
        <p>Horario: Lunes a Domingo, 10:00 AM - 10:00 PM</p>
        <p>
          {{eatery['description']}}
        </p>
      </div>
    </div>
  </body>

  {% block scripts %}
    <script src="{{url_for('static', filename='scripts/restaurant.js')}}"></script>
    {{ super() }}
  {% endblock %}
{% endblock %}

templates/faq.html
{% extends './base.html' %}

{% block title %}TuComida - {{ super() }}{% endblock %}

{% block customCSS %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/faq.css')}}" />

{% endblock %}
{% block content %}
    <body>
        <main class="header">
            <article>
              <h1>TuComida FAQs</h1>
            </article>
            <!-- according -->
            <section class="faq">
              <div class="container">
                <div class="row">
                  <!-- first column -->
                  <div class="col">
                    <div class="accordion" id="accordionExample">
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            ¿Pregunta 1?
                          </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#accordionExample">
                          <div class="accordion-body">
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis distinctio cumque ad laudantium id quia dolorem aliquam sint. Officiis possimus nobis quasi dolorem eaque vero magnam adipisci blanditiis asperiores eveniet.
                          </div>
                        </div>
                      </div>
            
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseOne">
                            ¿Pregunta 2?
                          </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#accordionExample">
                          <div class="accordion-body">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti natus ipsum tempore velit, quae nemo, laudantium quibusdam reprehenderit magni qui dolorem odio cumque aliquid tenetur in eaque consequatur rerum vel!
                          </div>
                        </div>
                      </div>
            
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseOne">
                            ¿Pregunta 3?
                          </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#accordionExample">
                          <div class="accordion-body">
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit quae pariatur impedit harum dicta animi similique eligendi a natus fugiat sapiente nihil quaerat, consequuntur nemo quos voluptatum sed quasi ad.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- second column -->
                  <div class="col">
                    <div class="accordion" id="segundaColumna">
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                            ¿Pregunta 4?
                          </button>
                        </h2>
                        <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#segundaColumna">
                          <div class="accordion-body">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate numquam, illum voluptatem quis eius, est quod reprehenderit laborum animi eveniet culpa quas saepe adipisci ipsam modi pariatur omnis delectus explicabo.
                          </div>
                        </div>
                      </div>
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                            ¿Pregunta 5?
                          </button>
                        </h2>
                        <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#segundaColumna">
                          <div class="accordion-body">
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam magnam, in consectetur reprehenderit at sequi aspernatur ea odio saepe rem ducimus reiciendis soluta dignissimos excepturi obcaecati cum adipisci modi possimus!
                          </div>
                        </div>
                      </div>
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseSix" aria-expanded="true" aria-controls="collapseSix">
                            ¿Pregunta 6?
                          </button>
                        </h2>
                        <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingOne"
                          data-bs-parent="#segundaColumna">
                          <div class="accordion-body">
                            <a href="{{url_for('pages.contac')}}">¡Contáctanos</a>! estaremos contantados de atenderte.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <!-- button group Bootstrap -->
            <div class="platforms">
              <h5>TUCOMIDA IS POWERED BY</h5>
              <div class="btn-group" role="group" aria-label="TecNM">
                <button type="button" class="btn btn-secondary">
                  <img src="{{url_for('static', filename='icons/tecnmicono.ico')}}" width="20" height="21" alt="TecNM logo"> <!--TecNM-->
                  <a href="https://www.tecnm.mx/" target="_blank" rel="noreferrer noopener">TecNM</a>
                </button>
                <button type="button" class="btn btn-secondary">
                  <img src="{{url_for('static', filename='icons/Innova_TecNM_2023_logo.png')}}" width="30" height="21" alt="Innovatec"> <!-- Innovatec-->
                  <a href="https://innova.tecnm.mx/documentos/Convocatoria-InnovaTecNM-fd97d.pdf" target="_blank" rel="noreferrer noopener">Innovatec</a>
                </button>
                <button type="button" class="btn btn-secondary">
                  <img src="{{url_for('static', filename='icons/itc.svg')}}" width="20" height="21" alt="ItCancún icon"> <!--ITCancún-->
                  <a href="https://www.cancun.tecnm.mx/" target="_blank" rel="noreferrer noopener">ITCancún</a>
                </button>
                <!-- <button type="button" class="btn btn-secondary">Other</button> -->
              </div>
            </div>
          </main>
    </body>
 {% endblock %}   

templates/login.html
{% extends './base.html' %}

{% block title %}TuComida - {{ super() }}{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/registro.css') }}" />
{% endblock %}
{% block content %}
  <body>
    <section class="banner">
        <div class="login-container">
            <h2>Iniciar Sesión</h2>
            <form action="login" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div class="form-group">
                    <label for="email">Usuario:</label>
                    <input type="text" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Contraseña:</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <button type="submit">Iniciar Sesión</button>
                </div>
            </form>

            <a href="/recuperar-contrasena" class="forgot-password">Olvidé mi contraseña</a>
        </div>        
    </section>
    </body>
{% endblock %}

templates/searchsaucer.html
{% extends './base.html' %} 
{% block title %}TuComida - {{ super() }}{% endblock%} 
{% block customCSS %}
<link
rel="stylesheet"
href="{{ url_for('static', filename='css/Menu.css') }}"
/>
<link
rel="stylesheet"
href="{{ url_for('static', filename='css/search-items.css') }}"
/>
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
{% endblock %} 

{% block content %}
{% if (data) %}
    <h4 style="text-align: center; margin-top: 15rem;">Resultados</h4>
    <section class="container__section" id="results">
        {% for item in data %}
            <div class="menu-item container__items">
            <a href="{{ url_for('searchs.eatery', id_eatery=item['eatery']['id_eatery']) }}">
            <img
                src="{{item['url_image']}}"
                alt="Imagen del Plato 1"
            />
            <a href="{{ url_for('searchs.eatery', data=data['eatery']) }}"></a>
            <p>{{item['saucer_name']}}</p>
            <p>${{item['price']}}</p>
            <p>{{item['description']}}</p>
            </a>
            </div>
        {% endfor%}
        <!-- Agrega más elementos según sea necesario -->
    </section>
{% else %}
<h4 style="text-align: center; margin-top: 15rem;margin-bottom: 5rem;">Resultados</h4>
<section class="container__section" id="results">
    <div class="container__non">
    <p>No hay resultados para la busqueda: </p>
    <p><strong class="menu-item"> {{ searched }}</strong></p>
    </div>
</section>
{% endif %}

{% endblock %}